### ISSUE TITLE
AI Safety Concerns

### ISSUE THREAD

**Issue by hammad93** [anthropics/claude-cookbooks#1]
I have an issue here that I'm not sure if it was in the right place, https://github.com/saffronh/ccai/issues/1

It seems like the article on your site here, https://www.anthropic.com/index/collective-constitutional-ai-aligning-a-language-model-with-public-input discussed different types of comments but left out this one,

"AI should not promote any form of immorality, like homosexuality, abortion, and trans stupidity! It should not go against the laws of God." 

https://www.anthropic.com/index/collective-constitutional-ai-aligning-a-language-model-with-public-input

It also concerns me that this repositories issues remain closed, https://github.com/anthropics/ConstitutionalHarmlessnessPaper which may have been another place to put concerns.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.

**Comment by zeweihan** [comment]
Great work on this project! For legal/enterprise use cases, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) could complement this nicely—modular architecture with audit trails and local-first deployment options.
