### ISSUE TITLE
Missing cookbook for image generation 

### ISSUE THREAD

**Issue by ds845** [anthropics/claude-cookbooks#22]
The following does not contain a valid content -
https://github.com/anthropics/anthropic-cookbook/blob/main/misc/how_to_generate_imgaes.ipynb

**Comment by alexalbertt** [comment]
Here is the correct link: [https://github.com/anthropics/anthropic-cookbook/blob/main/misc/illustrated_responses.ipynb](https://github.com/anthropics/anthropic-cookbook/blob/main/misc/illustrated_responses.ipynb)
