### ISSUE TITLE
404 on link from site

### ISSUE THREAD

**Issue by rgbkrk** [anthropics/claude-cookbooks#24]
On https://docs.anthropic.com/claude/docs/embeddings there's a link to https://github.com/anthropics/anthropic-cookbook/blob/main/third_party/voyageai/how_to_create_embeddings.md which should be https://github.com/anthropics/anthropic-cookbook/blob/main/third_party/VoyageAI/how_to_create_embeddings.md.

**Comment by alexalbertt** [comment]
Thanks! Fixed!
