### ISSUE TITLE
Chat Model - Remembering the context

### ISSUE THREAD

**Issue by QAInsights** [anthropics/claude-cookbooks#3]
Can we have an example of how Claude remembers the context so that the subsequent questions asked by humans can be answered by Claude? Thanks!

**Comment by QAInsights** [comment]
Why this is closed without any comments 😃

**Comment by alexalbertt** [comment]
Hi @QAInsights, in order to do this, you just have to keep the previous messages in the messages array on each subsequent API call to Claude. Claude doesn't "remember" the conversation by default -- you have to give it the whole conversation again on each API call.
