### ISSUE TITLE
Something is wrong wit the calculator_tool.ipynb cookbook

### ISSUE THREAD

**Issue by maxshatsky** [anthropics/claude-cookbooks#34]
Cookbook located at tool_use/calculator_tool.ipynb is unable to be opened from GitHub website, nor after downloading the file.
Hyperlink to the file: https://github.com/anthropics/anthropic-cookbook/blob/main/tool_use/calculator_tool.ipynb

The exact error displayed on GH website is:

Invalid Notebook
The Notebook Does Not Appear to Be Valid JSON
Using nbformat v5.10.4 and nbconvert v7.16.1

The exact error displayed in VS Code after attempt to open the file:

The editor could not be opened due to an unexpected error: Bad escaped character in JSON at position 1785 (line 61 column 39)

**Comment by alexalbertt** [comment]
Should be fixed now!
