### ISSUE TITLE
When using tools to get a structured response, the returned array sometimes becomes a string.

### ISSUE THREAD

**Issue by AsianLazyMan** [anthropics/claude-cookbooks#35]
Hi!
I found this error.
<img width="529" alt="image" src="https://github.com/anthropics/anthropic-cookbook/assets/42577440/3a633e17-c1a0-490f-aafa-71ccbe4bbac8">
The topics should be an array, as defined in the tool.
const tools: Tool[] = [
      {
        name: 'print_note_schema',
        description: 'Prints a article schema of the input document into well-structured JSON.',
        input_schema: {
          type: 'object',
          properties: {
            title: {
              type: 'string',
              description:
                'Title of this article schema. Should be as concise and precise as possible.',
            },
            summary: {
              type: 'string',
              description:
                'Summary of the input article.',
            },
            topics: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  subtitle: {
                    type: 'string',
                    description:
                      'Subtitle of the topic Should be as concise and precise as possible.And ensure that the topic can match the corresponding content in the summary.',
                  },
                  topicSummary: {
                    type: 'string',
                    description:
                      'Summary of the topic. Should be as concise and precise as possible.And ensure that the topic can match the corresponding content in the summary of this schema.',
                  },
                  markIds: {
                    type: 'string',
                    description:
                      'What is stored here is the id of the mark related to the current topic. The marks come from the <mark> tag in the input.If there are multiple corresponding marks, be sure to use "," to separate them.',
                  },
                  additionalSuggestions: {
                    type: 'string',
                    description:
                      'Apart from the input I gave you, what do you think can be expanded on this topic? This content is not required, so the content of the suggestions you give me needs to be non-redundant and to the point.If there are multiple corresponding additionalSuggestions, be sure to use "," to separate them.',
                  },
                },
                required: ['subtitle', 'topicSummary', 'markIds', 'additionalSuggestions'],
              },
              description:
                'Array of topics. Should be as specific as possible.And ensure that these topics can match the corresponding content in the summary.',
            },
          },
          required: ['title', 'summary', 'topics'],
        },
      },
    ];

**Comment by wavydeer** [comment]
I am having this issue as well is there any work around for this?
