### ISSUE TITLE
Example/Recipe for uploading attachments (docx, xlsx, csv, txt, html, odt, rtf, epub) via API

### ISSUE THREAD

**Issue by eyecantell** [anthropics/claude-cookbooks#79]
Looking around I am not finding documentation how to upload attachments (docx, csv, txt, html, odt, rtf, epub). There is the recipe for uploading a PDF, and uploading images (`image/jpeg`, `image/png`, `image/gif`, and `image/webp`) but not for the other types. If they are done the same way, the documentation offering an example or at least a description how to do so would be great. 

Attachments of these types can be easily uploaded to the console.
[Can I upload documents to Claude?](https://support.anthropic.com/en/articles/7996850-can-i-upload-documents-to-claude)

Hopefully they can also be uploaded via the API.

**Comment by eyecantell** [comment]
FWIW, Poe.com will actually let you interface with Anthropic Claude through their fastapi_poe::ProtocolMessage class, and add attachments:

```
import fastapi_poe as fp
...
        attachments = []
        for att in notice.attachments:
            mime_type = att.get_mime_type(persist.notice_dir_full_path(notice))
            # print(f"{mime_type=}")
            # print(f"{att.json()=}")
            download_url = self.get_download_url_with_parameters(notice, att)
            # print(f"{download_url=}")
            message_attachment = fp.Attachment(
                name=att.title,
                data=att.content,
                content_type=mime_type,
                url=download_url,
            )
            attachments.append(message_attachment)

        message.attachments = attachments
```
It may be that under the hood they are converting all of the file types to text/images before passing to Claude, but if the Anthropic API actually handles those file types, it would be great to open those API calls up so we can have direct access to it instead of working through a third party.

**Comment by alexalbertt** [comment]
The Anthropic API cannot handle those documents at the moment and any interface supporting upload is converting the files into text/images. Good idea to potentially add some recipes on that!
